[epdiy-patch] Hardcode config to ED047TC1.
I was unable to work around this error on the build side. The define is
in `sdkconfig.h`, but is not included in `epd_internals.h`.

```
error: failed to run custom build command for `esp-idf-rs v0.1.0 (/project)`

Caused by:
  process didn't exit successfully: `/project/target/debug/build/esp-idf-rs-b8414e569431348c/build-script-build` (exit status: 101)
  --- stderr
  ./components/epdiy/include/epd_internals.h:55:2: error: "no display type defined!"
  ./components/epdiy/include/epd_internals.h:55:2: error: "no display type defined!", err: true
  thread 'main' panicked at 'Couldn't generate bindings!: ()', build.rs:38:39
```